# Generated by Django 3.1.4 on 2021-02-18 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practica', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='index_one',
        ),
        migrations.RemoveField(
            model_name='user',
            name='index_two',
        ),
        migrations.RemoveField(
            model_name='user',
            name='middle_one',
        ),
        migrations.RemoveField(
            model_name='user',
            name='middle_two',
        ),
        migrations.RemoveField(
            model_name='user',
            name='pinky_one',
        ),
        migrations.RemoveField(
            model_name='user',
            name='pinky_two',
        ),
        migrations.RemoveField(
            model_name='user',
            name='ring_one',
        ),
        migrations.RemoveField(
            model_name='user',
            name='ring_two',
        ),
        migrations.AddField(
            model_name='user',
            name='fingers',
            field=models.CharField(default='0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0', max_length=128, null=True),
        ),
    ]
