# Generated by Django 3.1.4 on 2021-01-21 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('practica', '0002_ses'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Text_Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40)),
                ('middle_name', models.CharField(max_length=40, null=True)),
                ('last_name', models.CharField(max_length=40)),
                ('born_year', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Text_Mode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(max_length=30)),
            ],
        ),
        migrations.RenameModel(
            old_name='Ses',
            new_name='Session',
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(null=True)),
                ('text', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='texts_written', to='practica.text_author')),
                ('mode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='texts_in_mode', to='practica.text_mode')),
            ],
        ),
    ]
