# Generated by Django 3.1.4 on 2021-04-01 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practica', '0002_auto_20210401_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='answered_correctly',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
