# Generated by Django 3.1.4 on 2021-04-04 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practica', '0003_session_answered_correctly'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='leitner_box',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
